hbase:
  config:
    properties:
      hbase.zookeeper.quorum: hadoop-master:2181,hadoop-slave01:2181,hadoop-slave02:2181
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.16.38:8761/eureka/
    fetchRegistry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: nuclear-data
  config:
    enableRedis: true
    enableHBase: true
    enableSwagger2: true
    enableMybatisPlus: true
    enableServiceExtImpl: true
  #数据源
  datasource:
    url: jdbc:mysql://192.168.16.28:3306/nuclear_tw?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: aims2016
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: #默认连接池配置
      #连接池名称，默认HikariPool-1
      pool-name: defaultHikariPool
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 12
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 30000
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #连接测试查询
      connection-test-query: SELECT 1
      #自动提交
      auto-commit: true
  #MQ配置信息
  rabbitmq:
    host: 192.168.16.43
    port: 5672
    username: admin
    password: admin123$
    #开启手动ack,控制消息在MQ中的删除，重发...处理完毕
    listener:
      simple:
        acknowledge-mode: auto
  redis:
    cluster:
      nodes:
        - 192.168.16.43:6378
        - 192.168.16.43:6379
        - 192.168.16.44:6378
        - 192.168.16.44:6379
        - 192.168.16.45:6378
        - 192.168.16.45:6379
      max-redirects: 5
    password: aims2016
    timeout: 6000ms
    database: 15
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最小空闲连接
        min-idle: 20
        # 连接池中的最大空闲连接
        max-idle: 50
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.aimsphm.nuclear.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
feign:
  hystrix:
    enabled: true #feign开启hystrix支持
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
#ribbon的超时时间, 防止feign调用超时
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  #是否所有操作都重试
  OkToRetryOnAllOperations: false