spring:
  rabbitmq:
    addresses: 192.168.16.43
    username: admin
    password: admin123$
  main:
    allow-bean-definition-overriding: true
  config:
    enableRedis: true
    enableMybatisPlus: true
    enableServiceExtImpl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.16.28:3306/nuclear_tw?useUnicode=true&characterEncoding=utf8
    username: root
    password: aims2016
    hikari:
      pool-name: coreHikariPool
      maximum-pool-size: 12
      connection-timeout: 30000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
      auto-commit: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://192.168.16.43:8761/eureka/