server:
  port: 8083
  max-http-header-size: 10000000
scheduled:
  config:
    enable: true
    # 每小时的37分钟执行一次
    FanMonitorJob: 0 37 * * * ?
    # 每分钟的10秒执行一次
    FanStartStopStatusJob: 10 * * * * ?
    # 每小时的13分钟执行一次
    PumpMonitorJob: 0 13 * * * ?
    # 每分钟的37秒执行一次
    PumpStartStopStatusJob: 37 * * * * ?
spring:
  mybatisPlusConfig:
    enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: @sql_url@
    username: @sql_username@
    password: @sql_password@
    hikari:
      pool-name: coreHikariPool
      maximum-pool-size: 12
      connection-timeout: 30000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
      auto-commit: true
  rabbitmqconfig:
    enable: true
  rabbitmq:
    first:
      host: @rabbitmq_host1@
      port: 5672
      username: @rabbitmq_host1_username@
      password: @rabbitmq_host1_password@
    second:
      host: 192.168.16.45
      port: 5672
      username: admin
      password: admin123$
  redis:
    password: aims2016
    cluster:
      nodes:
        @redis1a@
        @redis1b@
        @redis2a@
        @redis2b@
        @redis3a@
        @redis3b@
      max-redirects: 5
    lettuce:
      pool:
        max-active: 200
        max-wait: 1000
        min-idle: 20
        max-idle: 50
  application:
    name: nuclear-core
  mail:
    host: 192.168.16.28
    port: 25
    username: mail@aimsphm.com
    password: Qazx1234
eureka:
  client:
    serviceUrl:
      defaultZone: @eureka_ip1@,@eureka_ip2@
    fetchRegistry: true
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath*:**/sqlmap/*.xml
  typeAliasesPackage: com.aimsphm.nuclear.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
ribbon:
  ConnectTimeout: 3000
  # 请求处理的超时时间
  ReadTimeout: 60000

