package com.aimsphm.nuclear.common.autoIncrKey;



public class BizAutoIncr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.sys_biz_auto_incr.id
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.sys_biz_auto_incr.biz_key
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    private String bizKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.sys_biz_auto_incr.value
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.sys_biz_auto_incr.id
     *
     * @return the value of public.sys_biz_auto_incr.id
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.sys_biz_auto_incr.id
     *
     * @param id the value for public.sys_biz_auto_incr.id
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.sys_biz_auto_incr.biz_key
     *
     * @return the value of public.sys_biz_auto_incr.biz_key
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public String getBizKey() {
        return bizKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.sys_biz_auto_incr.biz_key
     *
     * @param bizKey the value for public.sys_biz_auto_incr.biz_key
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public void setBizKey(String bizKey) {
        this.bizKey = bizKey == null ? null : bizKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.sys_biz_auto_incr.value
     *
     * @return the value of public.sys_biz_auto_incr.value
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.sys_biz_auto_incr.value
     *
     * @param value the value for public.sys_biz_auto_incr.value
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}