package com.aimsphm.nuclear.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.aimsphm.nuclear.common.autoIncrKey.BizAutoIncr;

@Mapper
public interface BizAutoIncrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_biz_auto_incr
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_biz_auto_incr
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    int insert(BizAutoIncr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_biz_auto_incr
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    int insertSelective(BizAutoIncr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_biz_auto_incr
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    BizAutoIncr selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_biz_auto_incr
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    int updateByPrimaryKeySelective(BizAutoIncr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_biz_auto_incr
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    int updateByPrimaryKey(BizAutoIncr record);

    BizAutoIncr selectByBizKey(String bizKey);
    
    int updateWithLagerValue(@Param("bizKey") String bizKey, @Param("value") int value);
    
    int deleteAll();
    
    int insertBatch(List<BizAutoIncr> bizAutoIncrs);
    
    List<BizAutoIncr> selectAll();
}