server:
  port: 8083
  max-http-header-size: 10000000
  servlet:
    context-path: /service
spring:
  application:
    name: core
  main:
    allow-bean-definition-overriding: true
  config:
    enableRedis: true
    enableSwagger2: true
    enableAlgorithm: true
    enableMybatisPlus: true
    enableDataService: true
    enableServiceExtImpl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: @db_url@
    username: @db_username@
    password: @db_password@
    hikari:
      pool-name: coreHikariPool
      maximum-pool-size: 12
      connection-timeout: 30000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
      auto-commit: true
  rabbitmq:
    host: @rabbitmq_host@
    port: 5672
    username: @mq_username@
    password: @mq_password@
  redis:
    host: @redis_host@
    password: @redis_password@
    lettuce:
      pool:
        max-active: 200
        max-wait: 1000
        min-idle: 20
        max-idle: 50
eureka:
  client:
    serviceUrl:
      defaultZone: @eureka_master@,@eureka_salver@
    fetchRegistry: true
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.aimsphm.nuclear.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
ribbon:
  ConnectTimeout: 3000
  # 请求处理的超时时间
  ReadTimeout: 60000

#CAS服务地址
cas:
  server:
    host:
      url: https://sso.casuat.jnpc.com.cn/cas
      #CAS服务登录地址
      login_url: ${cas.server.host.url}/login
      #CAS服务登出地址
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url}
  #应用访问地址
app:
  server:
    host:
      url: http://10.23.16.167:10086${server.servlet.context-path}
  #应用登录地址
  login_url: /login
  #应用登出地址
  logout_url: /logout

privileges-server-url: http://autogrant.jnpc.com.cn/autogrant/privileges/queryUserQXPrivileges.so