hbase:
  config:
    properties:
      hbase.zookeeper.quorum: @hbase_zk_quorum@
config:
  cron:
    # 每隔3分
    #   hourly: 0 0/3 * * * ?
    # 每小时的13分
    hourly: 0 43 * * * ?
    # 每天1点23分
    daily: 0 23 1 * * ?
    # 每周一的2点37分钟
    weekly: 0 37 2 ? * MON
    # 每月1号的3点47分
    monthly: 0 47 3 1 * ?
eureka:
  client:
    serviceUrl:
      defaultZone: @eureka_master@,@eureka_salver@
    fetchRegistry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: down-sample
  config:
    enableRedis: true
    enableHBase: true
    enableSwagger2: true
    enableAlgorithm: true
    enableServiceExtImpl: true
    enableMybatisPlusDynamicTable: true
  #数据源
  datasource:
    url: @db_url@
    username: @db_username@
    password: @db_password@
    db_dbSchema: @db_dbSchema@
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: #默认连接池配置
      #连接池名称，默认HikariPool-1
      pool-name: defaultHikariPool
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 12
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 30000
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #连接测试查询
      connection-test-query: SELECT 1
      #自动提交
      auto-commit: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.aimsphm.nuclear.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    banner: false
feign:
  hystrix:
    enabled: true #feign开启hystrix支持
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
#ribbon的超时时间, 防止feign调用超时
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  #是否所有操作都重试
  OkToRetryOnAllOperations: false